# Generated by Django 5.2.9 on 2026-01-29 02:58

import common.encoder.encoder
import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models

old = []
new = []

def _replace_tool_icons(apps, schema_editor):
    if len(old) != len(new):
        raise ValueError("`old` 与 `new` 长度不一致，无法一一替换")

    Tool = apps.get_model("tools", "Tool")
    mapping = dict(zip(old, new))

    # 逐个 update，避免依赖数据库对 CASE/WHEN 的兼容差异
    for old_icon, new_icon in mapping.items():
        Tool.objects.filter(icon=old_icon).update(icon=new_icon)

class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_alter_tool_tool_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolRecord',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='主键id')),
                ('source_type', models.CharField(choices=[('APPLICATION', 'Application'), ('KNOWLEDGE', 'Knowledge'), ('TRIGGER', 'Trigger')], default='APPLICATION', max_length=256, verbose_name='触发器任务类型')),
                ('source_id', models.UUIDField(verbose_name='资源id')),
                ('meta', models.JSONField(default=dict, encoder=common.encoder.encoder.SystemEncoder)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('REVOKE', 'Revoke'), ('REVOKED', 'Revoked')], default='STARTED', max_length=20, verbose_name='状态')),
                ('run_time', models.FloatField(default=0, verbose_name='运行时长')),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.tool')),
                ('workspace_id', models.CharField(db_index=True, default='default', max_length=64, verbose_name='工作空间id')),
            ],
            options={
                'db_table': 'tool_record',
            },
        ),
        migrations.RunPython(_replace_tool_icons, reverse_code=migrations.RunPython.noop),
    ]
