# Generated by Django 5.2.11 on 2026-02-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_taskrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='tool_type',
            field=models.CharField(choices=[('INTERNAL', '内置'), ('CUSTOM', '自定义'), ('SKILL', '技能'), ('MCP', 'MCP工具'), ('DATA_SOURCE', '数据源')], db_index=True, default='CUSTOM', max_length=20, verbose_name='工具类型'),
        ),
    ]
