# Generated by Django 5.2.9 on 2026-01-14 06:51

from django.db import migrations, models


def insert_default_data(apps, schema_editor):
    Application = apps.get_model('application', 'Application')
    # 批量修改 把所有的file_clean_time的值设置成clean_time的值
    Application.objects.all().update(file_clean_time=models.F('clean_time'))


class Migration(migrations.Migration):
    dependencies = [
        ('application', '0005_chatrecord_vote_other_content_chatrecord_vote_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='file_clean_time',
            field=models.IntegerField(default=180, verbose_name='文件清理时间'),
        ),
        migrations.RunPython(insert_default_data)
    ]
