# Generated by Django 5.2.8 on 2026-01-16 06:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_application_file_clean_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationapikey',
            name='expire_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='过期时间'),
        ),
        migrations.AddField(
            model_name='applicationapikey',
            name='is_permanent',
            field=models.BooleanField(default=True, verbose_name='是否永久'),
        ),
    ]
