# Generated by Django 5.2.8 on 2026-01-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_applicationapikey_expire_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='ip_address',
            field=models.CharField(default='', max_length=128, verbose_name='ip地址'),
        ),
        migrations.AddField(
            model_name='chat',
            name='source',
            field=models.JSONField(default=dict, verbose_name='来源'),
        ),
        migrations.AddField(
            model_name='chatrecord',
            name='ip_address',
            field=models.CharField(default='', max_length=128, verbose_name='ip地址'),
        ),
        migrations.AddField(
            model_name='chatrecord',
            name='source',
            field=models.JSONField(default=dict, verbose_name='来源'),
        ),
    ]
