# Generated by Django 5.2.11 on 2026-02-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_chatsharelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='skill_tool_ids',
            field=models.JSONField(default=list, verbose_name='技能ID列表'),
        ),
        migrations.AddField(
            model_name='applicationversion',
            name='skill_tool_ids',
            field=models.JSONField(default=list, verbose_name='技能ID列表'),
        ),
    ]
